DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS resources;

CREATE TABLE events(
    id SERIAL PRIMARY KEY,
    username TEXT NOT NULL,
    body TEXT NOT NULL,
    user_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT
)

CREATE TABLE resources(
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    user_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT
)